name: Docker Image CI
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag markmcdevops/workshop8
    - name: Docker push
      run: docker push markmcdevops/workshop8
    - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
        usedocker: true
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}} #Must be unique in Heroku 
        heroku_email: ${{secrets.HEROKU_EMAIL}}